name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 9:10pm in India (3:40pm UTC)
    - cron: "40 15 * * *"

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
          REPOSITORY: Purbayan2014/Purbayan2014
          SHOW_TITLE: true
          BLOCKS: ->
          TIME_RANGE: all_time
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          LANG_COUNT: 10
